---
- name: Déploiement de la stack Monitoring - NAS-HomeServer
  hosts: localhost
  connection: local
  tasks:
    - name: Création des répertoires de données
      # Utilise sudo pour garantir la création sur /volume1/docker
      become: true 
      file:
        path: "{{ item }}"
        state: directory
        owner: "1026"
        group: "100"
        mode: '0755'
      loop:
        - /volume1/docker/prometheus/config
        - /volume1/docker/prometheus/data
        - /volume1/docker/grafana

    - name: Copie de la configuration Prometheus
      # On cherche le fichier à la racine du dépôt désormais
      copy:
        src: prometheus.yml 
        dest: /volume1/docker/prometheus/config/prometheus.yml
        owner: "1026"
        group: "100"
        mode: '0644'

    - name: Vérification des droits sur le dossier Grafana
      # Étape cruciale pour éviter que Grafana ne puisse pas écrire sa base SQL
      become: true
      file:
        path: /volume1/docker/grafana
        state: directory
        owner: "1026"
        group: "100"
        recurse: yes

    - name: Lancement de la stack via Docker Compose
      # On utilise le fichier à la racine
      # Le flag --wait vérifie que Prometheus et Grafana démarrent bien
      command: docker compose -f docker-compose.yml up -d --remove-orphans --wait
