---
- name: "IaC - Deploiement Stack Monitoring Zabbix"
  hosts: localhost
  connection: local
  become : yes

  tasks:
    - name: "Creation des repertoires pour Zabbix"
      file:
        path: "/volume1/docker/zabbix/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - 'db_data'
        - 'alertscripts'

    - name: "Creation du repertoire pour Grafana"
      file:
        path: "/volume1/docker/grafana"
        state: directory
        mode: '0755'

    - name: "Gestion de la Stack Docker Compose (Zabbix & Grafana)"
      community.docker.docker_compose_v2:
        project_src: "/app"
        project_name: "monitoring-homeserver"
        state: present
        pull: missing
        remove_orphans: true 
