- name: "IaC - Deploiement Stack Monitoring Zabbix"
  hosts: localhost
  connection: local

  vars:
    zabbix_version: "alpine-7.4.9"
    grafana_version: "11.6.1"

  tasks:
    - name: "Creation des repertoires pour Zabbix"
      file:
        path: "/volume1/docker/zabbix/{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - 'db_data'
        - 'alertscripts'

    - name: "Creation du repertoire pour Grafana"
      file:
        path: "/volume1/docker/grafana"
        state: directory
        mode: '0755'

    - name: "Creation du repertoire pour Prometheus"
      file:
        path: "/volume1/docker/prometheus/{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - 'config'
        - 'data'

    - name: "Creation du repertoire pour SNMP Exporter"
      file:
        path: "/volume1/docker/snmp"
        state: directory
        mode: '0755'

    - name: "Gestion de la Stack Docker Compose (Zabbix & Grafana)"
      community.docker.docker_compose_v2:
        project_src: "/app"
        project_name: "monitoring-homeserver"
        state: present
        pull: missing
        remove_orphans: true
      environment:
        DOCKER_API_VERSION: "1.43"
        ZABBIX_VERSION: "{{ zabbix_version }}"
        GRAFANA_VERSION: "{{ grafana_version }}"