version: '3.8'

# Définition des variables communes (Don't Repeat Yourself)
x-common-env: &common-env
  PUID: 1026
  PGID: 100
  TZ: Europe/Paris

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "1026:100" # Les droits qu'on a fixés tout à l'heure
    ports:
      - "9090:9090"
    volumes:
      # LA LIGNE CRUCIALE : NAS -> CONTENEUR
      - /volume1/docker/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      # Le dossier pour stocker la base de données (l'historique)
      - /volume1/docker/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3001:3000 # Accès via http://IP_DU_NAS:3001
    environment:
      <<: *common-env
    volumes:
      - /volume1/docker/grafana:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    network_mode: host # Indispensable pour que Prometheus lise les métriques du NAS
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)'
