services:
  # --- BLOC ZABBIX --- 
  zabbix-db:
    image: mariadb:10.6
    container_name: zabbix-db
    ports:
      - "3306:3306"
    restart: unless-stopped
    command: --character-set-server=utf8 --collation-server=utf8_bin --default-authentication-plugin=mysql_native_password
    volumes:
      - /volume1/docker/zabbix/db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd 
      - MYSQL_ROOT_PASSWORD=root_pwd 
    deploy:
      resources:
        limits:
          memory: 512M

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-7.0-latest 
    container_name: zabbix-server
    restart: unless-stopped
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
    environment:
      - DB_SERVER_HOST=127.0.0.1
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - MYSQL_ROOT_PASSWORD=root_pwd
    deploy:
      resources:
        limits:
          memory: 256M

  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:alpine-7.0-latest
    container_name: zabbix-web
    restart: unless-stopped
    ports:
      - "8085:8080"
    environment:
      - DB_SERVER_HOST=zabbix-db
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - MYSQL_ROOT_PASSWORD=root_pwd
      - ZBX_SERVER_HOST=127.0.0.1
      - PHP_TZ=Europe/Paris
    deploy:
      resources:
        limits:
          memory: 256M

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-7.0-latest
    container_name: zabbix-agent
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - ZBX_HOSTNAME=Synology-NAS
      - ZBX_SERVER_HOST=127.0.0.1
    deploy:
      resources:
        limits:
          memory: 64M

  # --- BLOC PROMETHEUS ---
  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: prometheus
    user: "root"
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - /volume1/docker/prometheus/config:/etc/prometheus
      - /volume1/docker/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.no-lockfile'
    deploy:
      resources:
        limits:
          memory: 512M

  node-exporter:
    image: prom/node-exporter:v1.9.0
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    deploy:
      resources:
        limits:
          memory: 32M

  # --- BLOC VISUALISATION ---
  grafana:
    image: grafana/grafana-oss:11.5.0
    container_name: grafana
    restart: unless-stopped
    user: "1026:100"
    ports:
      - "3001:3000"
    environment:
      - TZ=Europe/Paris
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    volumes:
      - /volume1/docker/grafana:/var/lib/grafana
    depends_on:
      - prometheus
      - zabbix-server
    deploy:
      resources:
        limits:
          memory: 512M
