FROM alpine/ansible:2.21.0@sha256:5c84cb25709b0eceaa7442508e23c8b79edb137d00a9b497c35fec0e3fb281be
RUN apk update && apk upgrade --no-cache && \
    apk add --no-cache docker-cli docker-cli-compose
COPY . /app
WORKDIR /app
