FROM alpine/ansible:2.21.0@sha256:1a8ac3fd28c217210a9530b385f57d4b8afbe13956e5f0043063d98f5bd71bd5
RUN apk update && apk upgrade --no-cache && \
    apk add --no-cache docker-cli docker-cli-compose
COPY . /app
WORKDIR /app
