name: Deploiement Automatique Monitoring
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Nettoyage du repertoire sur Volume1
        run: |
          mkdir -p /volume1/docker/monitoring_workspace
          rm -rf /volume1/docker/monitoring_workspace/*

      - name: Recuperation du code (Fallback Curl)
        run: |
          cd /volume1/docker/monitoring_workspace
          curl -f -L -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" \
            https://api.github.com/repos/NAS-HomeServer/Monitoring_HomeServer/tarball/main -o repo.tar.gz
          tar -xzf repo.tar.gz --strip-components=1
          rm repo.tar.gz

      - name: Execution Ansible via Docker (Nettoyage Force + DooD)
        run: |
          cd /volume1/docker/monitoring_workspace
          
          # 1. On crée le Dockerfile jetable
          cat << 'EOF' > Dockerfile
          FROM alpine/ansible:latest
          RUN apk add --no-cache docker docker-compose
          COPY . /monitoring-homeserver
          WORKDIR /monitoring-homeserver
          EOF
          
          # 2. On compile l'image
          docker build -t ansible-monitoring-tmp .
          
          # 3. LE COUP DE BALAI : On arrête tout ce qui porte le nom de ta stack avant
          # On ignore les erreurs si rien n'existe (|| true)
          docker stop node-exporter cadvisor prometheus grafana || true
          docker rm node-exporter cadvisor prometheus grafana || true
          
          # 4. On lance Ansible avec la compatibilité API 1.41
          docker run --rm \
            -e ANSIBLE_HOST_KEY_CHECKING=False \
            -e DOCKER_API_VERSION=1.41 \
            -v ~/.ssh:/root/.ssh:ro \
            -v /var/run/docker.sock:/var/run/docker.sock \
            ansible-monitoring-tmp \
            ansible-playbook -i hosts.ini deploy-monitoring.yml
