name: Deploiement Automatique Monitoring (Zabbix Stack)
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Nettoyage du repertoire sur Volume1
        run: |
          mkdir -p /volume1/docker/monitoring_workspace
          rm -rf /volume1/docker/monitoring_workspace/*

      - name: Recuperation du code (Fallback Curl)
        run: |
          cd /volume1/docker/monitoring_workspace
          curl -f -L -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" \
            https://api.github.com/repos/NAS-HomeServer/Monitoring_HomeServer/tarball/main -o repo.tar.gz
          tar -xzf repo.tar.gz --strip-components=1
          rm repo.tar.gz

      - name: Execution Ansible via Docker
        run: |
          cd /volume1/docker/monitoring_workspace
          
          # --- DEBOGAGE ---
          echo "==== CONTENU DU DOSSIER APRES TELECHARGEMENT GITHUB ===="
          ls -la
          echo "========================================================"
          # ----------------
          
          cat << 'EOF' > Dockerfile
          FROM alpine/ansible:latest
          RUN apk add --no-cache docker docker-compose
          EOF
          
          docker build -t ansible-runner-tmp .
          
          docker run --rm \
            -e ANSIBLE_HOST_KEY_CHECKING=False \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v /volume1/docker/monitoring_workspace:/app \
            -v /volume1/docker:/volume1/docker \
            -w /app \
            ansible-runner-tmp \
            ansible-playbook -i hosts.ini deploy-monitoring.yml