name: Deploiement Automatique Monitoring
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Preparation du repertoire
        run: |
          mkdir -p ./deploy_workspace_monitoring
          rm -rf ./deploy_workspace_monitoring/*

      - name: Recuperation du code
        run: |
          cd ./deploy_workspace_monitoring
          curl -L -u "axelginepro:${{ secrets.MY_GITHUB_TOKEN }}" \
            https://api.github.com/repos/NAS-HomeServer/Monitoring_HomeServer/tarball/main -o repo.tar.gz
          # Si l'extraction échoue, on affiche le contenu du fichier pour lire l'erreur
          tar -xzf repo.tar.gz --strip-components=1 || (cat repo.tar.gz && exit 1)

      - name: Execution Ansible
        run: |
          cd ./deploy_workspace_monitoring
          # On appelle directement les fichiers s'ils sont à la racine
          ansible-playbook -i hosts.ini deploy-monitoring.yml
